name: flavors_course
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  change_app_package_name: ^1.5.0
  flutter_flavorizr: 2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/common/
    - path: assets/flavors/dev/
      flavors:
        - dev
    - path: assets/flavors/prod/
      flavors:
        - prod
    - path: assets/flavors/stg/
      flavors:
        - stg




flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "Flavors Course Dev"
      android:
        applicationId: "highqapps.flavors.course.dev"
        icon: "assets/flavors/dev/app-icon.png"
        adaptiveIcon:
          foreground: "assets/flavors/dev/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "highqapps.flavors.course.dev"
        icon: "assets/flavors/dev/app-icon.png"

    stg:
      app:
        name: "Flavors Course Stg"
      android:
        applicationId: "highqapps.flavors.course.stg"
        icon: "assets/flavors/stg/app-icon.png"
        adaptiveIcon:
          foreground: "assets/flavors/stg/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "highqapps.flavors.course.stg"
        icon: "assets/flavors/stg/app-icon.png"

    prod:
      app:
        name: "Flavors Course"
      android:
        applicationId: "highqapps.flavors.course"
        icon: "assets/flavors/prod/app-icon.png"
        adaptiveIcon:
          foreground: "assets/flavors/prod/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "highqapps.flavors.course"
        icon: "assets/flavors/prod/app-icon.png"
